"""Skills generated from a shared feature-surface shape.

These are built by `_feature_surface_skill()` rather than written out field by
field, because they share a fixed contract and differ only in subject. Keeping
them beside - not inside - the hand-written catalog is what makes the difference
visible: a reader can tell at a glance which skills are bespoke and which follow
the surface template.
"""

from __future__ import annotations

from .catalog_types import _feature_surface_skill

_FEATURE_SURFACE_SKILLS = (
    _feature_surface_skill(
        "github-event-ops",
        "Hermes GitHub event operations workflow: route PR, issue, CI, and review webhook events into triage, review, or fix handoff cards.",
        (
            "github-event-ops",
            "github event ops",
            "github ops",
            "github triage",
            "github pr",
            "github review",
            "github action",
            "github actions",
            "pr opened",
            "pull request opened",
            "pull request review",
            "pr review",
            "ci failed",
            "check failed",
            "checks failed",
            "failing checks",
            "issue opened",
            "issue triage",
            "pull request webhook",
            "github webhook",
            "github issue",
            "github issue to pr",
            "auto review pr",
            "label issue",
            "label pr",
            "ci analysis",
            "fix handoff",
            "review handoff",
            "깃허브",
            "깃허브 pr",
            "깃허브 이슈",
            "github issue 들어온",
            "이슈 라벨",
            "pr 리뷰",
            "리뷰 라벨",
            "픽스 핸드오프",
            "ci 실패",
        ),
        "Use when Hermes receives or is asked to reason about GitHub PR, issue, review, or CI events and must choose review, triage, or fix-handoff without claiming a bot ran.",
        category="github-ops",
        phase="event-routing",
        next_action="prepare_github_event_ops_card",
        boundary="A GitHub event ops card is not webhook delivery, GitHub API mutation, review completion, label application, CI rerun, or fix execution evidence. When a fix is owned by Hermes coding, read `hermes_coding_harness/v1` before reporting build, review, CI, PR, or merge state.",
        good_prompt="github-event-ops PR opened with failing CI; triage whether this needs review or fix handoff.",
        bad_prompt="github-event-ops prove the issue was labelled and CI was rerun.",
    ),
    _feature_surface_skill(
        "agent-board",
        "Hermes agent board workflow: coordinate multiple Hermes profiles or agents with task, handoff, heartbeat, blocker, and completion states.",
        (
            "agent-board",
            "agent board",
            "kanban",
            "multi-agent",
            "multi agent",
            "multi agent board",
            "multiple hermes agents",
            "multiple hermes profiles",
            "hermes profiles",
            "subagent",
            "subagents",
            "sub agent",
            "sub agents",
            "agent coordination",
            "agent task board",
            "task board",
            "roles and board",
            "role board",
            "heartbeat",
            "blocker",
            "agent blocker",
            "agent heartbeat",
            "agent handoff",
            "handoff board",
            "interviewer reviewer builder",
            "reviewer builder",
            "칸반",
            "멀티 에이전트",
            "서브에이전트",
            "서브 에이전트",
            "여러 에이전트",
            "Hermes agent 여러 명",
            "여러 명이 같이 일",
            "에이전트 보드",
            "작업 배분",
            "역할 배분",
            "작업 보드",
            "역할과 보드",
            "역할 보드",
        ),
        "Use when multiple Hermes profiles, agents, or targets need a board-shaped status contract for collaborative work.",
        category="agent-coordination",
        phase="board-status",
        next_action="prepare_agent_board_card",
        boundary="An agent board card is not proof that another Hermes agent accepted, executed, heartbeat-ed, or completed work unless target-specific evidence exists.",
        good_prompt="agent-board coordinate PM, CTO, QA, and release agents on this launch checklist.",
        bad_prompt="agent-board mark the other agent complete without an observed heartbeat or result.",
    ),
    _feature_surface_skill(
        "memory-new",
        "Hermes new-memory capture workflow: add reviewed project, product, or durable context candidates through capture, review, and approve actions.",
        (
            "memory-new",
            "new memory",
            "project memory",
            "product memory",
            "remember this project",
            "remember this product",
            "memory capture",
            "capture memory",
            "save project memory",
            "save product memory",
            "project context memory",
            "product context memory",
            "add memory candidate",
            "프로젝트 메모리 저장",
            "제품 메모리 저장",
            "프로젝트 기억",
            "제품 기억",
            "새 기억",
            "기억 추가",
            "메모리 캡처",
        ),
        "Use when the user wants to add new durable project, product, or context memory as an OMH project-memory candidate, with optional separate Hermes native-memory capture after review.",
        category="memory",
        phase="candidate-capture",
        next_action="prepare_memory_new",
        boundary="An OMH project-memory candidate is prepared local context only; it does not mutate Hermes internal memory, and optional Hermes native-memory capture requires separate observed approval and write evidence.",
        good_prompt="memory-new capture this product decision as a project-memory candidate for review.",
        bad_prompt="memory-new claim Hermes already remembers this internally without an observed native-memory write.",
        expected_outputs=(
            "memory_new_candidate/v1",
            "capture/review/approve decision",
            "OMH project-memory and optional Hermes native-memory targets",
            "prepared-vs-observed boundary",
        ),
        artifact_expectations=("memory_new_candidate/v1 metadata-only candidate when recorded",),
        extra_safety_rules=(
            "Add candidates before approval; do not present capture as an approved OMH project-memory record.",
            "Keep OMH project memory and Hermes native memory as separate stores with separate write evidence.",
        ),
        extra_quality_bar=(
            "Name the durable fact, project or product scope, source context, target store, review decision, and duplication or conflict check.",
        ),
    ),
    _feature_surface_skill(
        "memory-sync",
        "Hermes existing-memory curation workflow: review stale, conflicting, duplicate, overgeneralized, or risky USER.md, MEMORY.md, and skill memories through approve/reject/update actions.",
        (
            "memory-sync",
            "memory curation",
            "memory review",
            "memory inspect",
            "memory check",
            "memory update",
            "context cleanup",
            "curate memory",
            "stale memory",
            "hermes remembers",
            "conflicting memory",
            "duplicate skill",
            "MEMORY.md",
            "USER.md",
            "기억하고 있는",
            "기억하고 있는 프로젝트 맥락",
            "기억하는 맥락",
            "현재 hermes가 기억하는 맥락",
            "현재 헤르메스가 기억하는 맥락",
            "헤르메스가 기억하는 맥락",
            "오래된 맥락",
            "오래된 기억",
            "기억 점검",
            "기억 정리",
            "메모리 업데이트",
            "메모리 검사",
            "메모리 점검",
            "메모리 정리",
            "맥락 점검",
            "맥락 정리",
            "맥락 피드백",
            "등록된 맥락",
            "헤르메스 기억",
            "중복 스킬",
            "나에 대해 잘못 알고",
            "저장된 내 정보",
            "너한테 저장된",
            "저장된 프로필",
            "기억 바로잡",
            "what you remember about me",
            "your memory about me",
        ),
        "Use when existing Hermes USER.md, MEMORY.md, or accumulated skill memories need human-approved audit and cleanup. Do not use for adding new project or product memory candidates. 캡: MEMORY.md ~2,200자 / USER.md ~1,375자.",
        category="memory",
        phase="curation-review",
        next_action="prepare_memory_sync",
        boundary="A memory curation review is not Hermes internal memory, MEMORY.md, USER.md, or skill-file modification evidence until an approved write is observed.",
        good_prompt="memory-sync inspect stale project memories and ask me what to keep.",
        bad_prompt="memory-sync silently delete all conflicting memories.",
        extra_safety_rules=(
            "각 클레임은 원문 그대로 인용한다; 세션에 실제 근거가 있을 때만 출처를 언급한다.",
            "승인 전에는 어떤 파일도 수정하지 않는다; 승인 후 1회 일괄 쓰기로만 반영한다.",
        ),
        extra_quality_bar=(
            "출처를 추정하거나 지어내지 않는다; 근거 없는 클레임은 의심 항목으로만 제시한다.",
        ),
    ),
    _feature_surface_skill(
        "gateway-intent-card",
        "Hermes gateway intent workflow: normalize Discord, Slack, Telegram, and other gateway sessions into origin, thread, delivery, silent, attachment, and status-update policy.",
        (
            "gateway-intent-card",
            "gateway intent",
            "discord thread",
            "slack thread",
            "telegram delivery",
            "discord delivery policy",
            "slack delivery policy",
            "telegram delivery policy",
            "discord status update",
            "slack status update",
            "telegram status update",
            "gateway delivery",
            "gateway notification",
            "channel delivery",
            "session delivery",
            "silent update",
            "attachment policy",
            "status update policy",
            "webhook delivery",
            "게이트웨이",
            "디스코드",
            "슬랙",
            "텔레그램",
            "알림",
            "전달",
            "채널",
            "조용히",
            "스레드",
            "보내줘",
        ),
        "Use when Hermes needs platform-neutral gateway policy for a chat session, thread, delivery target, attachment, or status update.",
        category="gateway",
        phase="intent-card",
        next_action="prepare_gateway_intent_card",
        boundary="A gateway intent card is not platform login, message send, thread mutation, attachment upload, or delivery evidence.",
        good_prompt="gateway-intent-card route this Discord thread update silently unless action is needed.",
        bad_prompt="gateway-intent-card prove the Telegram attachment was sent.",
    ),
    _feature_surface_skill(
        "executor-runtime-readiness",
        "Hermes executor runtime readiness workflow: compare Codex, Claude Code, Hermes coding, and oh-my runtimes by available tools, missing tools, and handoff mode.",
        (
            "executor-runtime-readiness",
            "executor readiness",
            "runtime readiness",
            "codex readiness",
            "claude code readiness",
            "hermes coding readiness",
            "executor tools",
            "missing tools",
            "missing runtime tools",
            "runtime tools",
            "coding agent readiness",
            "coding runtime",
            "handoff mode",
            "handoff readiness",
            "codex or claude",
            "codex vs claude",
            "codex tools",
            "claude code tools",
            "hermes coding",
            "agent runtime",
            "subagent readiness",
            "worktree readiness",
            "codex로 넘길지 claude",
            "claude code로 넘길지 codex",
            "codex랑 claude",
            "claude code 중",
            "넘길지 codex",
            "넘길지 claude",
            "runtime migration",
            "omx",
            "omc",
            "omo",
            "코덱스",
            "클로드 코드",
            "헤르메스 코딩",
            "코딩 에이전트",
            "서브에이전트",
            "작업트리",
            "준비성",
            "실행 런타임",
            "어떤 런타임",
            "런타임으로 넘겨",
        ),
        "Use when a user may choose Codex, Claude Code, Hermes coding, or another runtime and needs tool/credential gaps before handoff.",
        category="executor-readiness",
        phase="runtime-selection",
        next_action="prepare_executor_runtime_readiness",
        boundary="Runtime readiness is not executor dispatch, plugin load, tool invocation, repository mutation, review, CI, or merge evidence.",
        good_prompt="executor-runtime-readiness can this task run in Codex, Claude Code, or Hermes coding?",
        bad_prompt="executor-runtime-readiness claim Codex already started the session.",
    ),
    _feature_surface_skill(
        "deliverable-package",
        "Hermes deliverable package workflow: track PPT, PDF, XLSX, DOCX, HWP, Markdown, and attachments through prepared, generated, QA, approved, and attached states.",
        (
            "deliverable-package",
            "deliverable mode",
            "file attachment",
            "attach file",
            "attachment status",
            "file delivery",
            "file deliverable status",
            "generated file",
            "첨부",
            "첨부 상태",
            "전달 상태",
        ),
        "Use when Hermes should prepare, request generation, QA, and report attachment status for user-visible file deliverables.",
        category="deliverables",
        phase="package-status",
        next_action="prepare_deliverable_package",
        boundary="A deliverable package card is not binary generation, render QA, formula recalculation, approval, upload, attachment, or delivery evidence.",
        good_prompt="deliverable-package turn this research into PPT and PDF with attachment status.",
        bad_prompt="deliverable-package claim the PDF was attached without observed file evidence.",
    ),
    _feature_surface_skill(
        "voice-operator",
        "Hermes voice operator workflow: turn short voice or mobile commands into clarify, plan, status, handoff, or confirmation actions.",
        (
            "voice-operator",
            "voice operator",
            "voice-first",
            "voice command",
            "mobile command",
            "short command",
            "dictated command",
            "dictated request",
            "spoken request",
            "speech command",
            "accessibility",
            "hands free",
            "hands-free",
            "phone command",
            "phone request",
            "push command",
            "음성",
            "음성으로",
            "음성 명령",
            "모바일",
            "모바일 명령",
            "핸드폰",
            "폰으로",
            "말로",
            "말로 한 요청",
            "접근성",
            "짧은 명령",
            "짧게 말한 요청",
        ),
        "Use when Hermes receives terse voice/mobile-style requests and should produce concise clarification, plan, or status UX.",
        category="accessibility",
        phase="voice-routing",
        next_action="prepare_voice_operator_card",
        boundary="A voice operator card is not speech recognition, mobile notification delivery, platform action, or accepted execution evidence.",
        good_prompt="voice-operator 'release before lunch, check risky parts' from mobile.",
        bad_prompt="voice-operator assume the user approved a destructive action from a vague voice note.",
    ),
    _feature_surface_skill(
        "browser-operator",
        "Hermes browser operator workflow: scope URL opening, page interaction, login/form boundaries, observations, and destructive confirmation gates.",
        (
            "browser-operator",
            "browser operator",
            "browser task",
            "browser operation",
            "browser automation",
            "browser session",
            "webpage operation",
            "web page operation",
            "open url",
            "open the url",
            "open page",
            "open the page",
            "visit url",
            "visit page",
            "navigate url",
            "navigate page",
            "click page",
            "click this page",
            "click button",
            "click login",
            "login page",
            "fill form",
            "fill the form",
            "submit form",
            "checkout url",
            "capture blockers",
            "page blockers",
            "interactive page",
            "browser trace",
            "browser observation",
            "playwright task",
            "웹페이지",
            "웹 페이지",
            "브라우저",
            "브라우저 작업",
            "브라우저 조작",
            "페이지 열고",
            "url 열고",
            "링크 열고",
            "클릭",
            "로그인",
            "로그인 폼",
            "폼 작성",
            "폼 입력",
            "캡처",
            "막히는 부분",
        ),
        "Use when Hermes should prepare or supervise a browser/page interaction request such as opening a URL, clicking, logging in, filling forms, or capturing page blockers without claiming browser execution.",
        category="browser",
        phase="browser-task",
        next_action="prepare_browser_operator_card",
        boundary="A browser operator card is not browser launch, login, credential validation, page mutation, form submission, purchase/payment/destructive action, screenshot, scraping, or successful interaction evidence unless an observed browser trace records it.",
        good_prompt="browser-operator open the staging checkout URL, click login, fill the form, and capture blockers.",
        bad_prompt="browser-operator use saved credentials and submit the production payment form without confirmation.",
        expected_outputs=(
            "browser_task_card/v1",
            "browser_interaction_scope/v1",
            "browser_auth_boundary/v1",
            "browser_observation_manifest/v1 when observed",
            "browser_confirmation_gate/v1 when destructive",
            "next action",
            "prepared-vs-observed boundary",
        ),
        artifact_expectations=(
            "browser_task_card/v1 metadata-only wrapper card when prepared",
            "browser_interaction_scope/v1 with target URL, allowed actions, stop condition, and prohibited actions",
            "browser_auth_boundary/v1 separating supplied credentials, missing credentials, and credential-use prohibition",
            "browser_observation_manifest/v1 only when screenshots, DOM notes, console/network traces, or click traces are observed",
        ),
        final_checklist=(
            "The target URL, allowed interactions, prohibited interactions, auth boundary, and stop condition are explicit.",
            "Credentials, login, payment, purchase, destructive submission, scraping, and data export are gated or marked missing.",
            "Screenshots, DOM state, console/network logs, and click/form traces are reported only from observed browser evidence.",
        ),
        recovery_notes=(
            "If no URL or target page is supplied, ask for the smallest target needed before opening a browser task.",
            "If login, payment, destructive mutation, or credential use is requested, require an explicit confirmation gate and do not proceed from vague intent.",
            "If the request is visual correctness rather than general page operation, route to visual-qa instead.",
        ),
    ),
    _feature_surface_skill(
        "workspace-file-operator",
        "Hermes workspace file operator workflow: scope local file/folder listing, search, organize, copy, move, rename, and delete tasks with path and destructive-action gates.",
        (
            "workspace-file-operator",
            "workspace file operator",
            "file operator",
            "file operation",
            "file operations",
            "filesystem task",
            "filesystem operation",
            "file system task",
            "file system operation",
            "list files",
            "list folder",
            "list directory",
            "find local files",
            "search files",
            "organize files",
            "organize folder",
            "move file",
            "move files",
            "copy file",
            "copy files",
            "rename file",
            "rename files",
            "delete file",
            "delete files",
            "remove file",
            "remove files",
            "archive files",
            "downloads folder",
            "reports folder",
            "folder cleanup",
            "file cleanup",
            "파일 작업",
            "파일 조작",
            "파일 정리",
            "파일 검색",
            "파일 찾아",
            "파일 이동",
            "파일 복사",
            "파일 이름 변경",
            "파일 삭제",
            "폴더 정리",
            "다운로드 폴더",
            "디렉터리 목록",
        ),
        "Use when Hermes should prepare or supervise local workspace/file-system operations such as listing, searching, organizing, copying, moving, renaming, archiving, or deleting files without claiming the operation ran.",
        category="filesystem",
        phase="file-task",
        next_action="prepare_workspace_file_operator_card",
        boundary="A workspace file operator card is not file read, file write, copy, move, rename, delete, archive, upload, download, permission change, or destructive filesystem evidence unless observed file-operation output records it.",
        good_prompt="workspace-file-operator list files in the reports folder and move old PDFs into archive after confirmation.",
        bad_prompt="workspace-file-operator delete every matching file without path scope or confirmation.",
        expected_outputs=(
            "workspace_file_task_card/v1",
            "file_operation_scope/v1",
            "file_observation_manifest/v1 when observed",
            "file_confirmation_gate/v1 when destructive",
            "next action",
            "prepared-vs-observed boundary",
        ),
        artifact_expectations=(
            "workspace_file_task_card/v1 metadata-only wrapper card when prepared",
            "file_operation_scope/v1 with path root, allowed operations, excluded paths, and stop condition",
            "file_observation_manifest/v1 only when directory listings, file stats, hashes, diffs, or operation output are observed",
            "file_confirmation_gate/v1 for delete, overwrite, move, rename, chmod, archive mutation, or irreversible cleanup",
        ),
        final_checklist=(
            "The path root, allowed file operations, excluded paths, destructive-operation policy, and stop condition are explicit.",
            "Delete, overwrite, move, rename, permission change, archive mutation, upload, and download are gated or marked missing.",
            "Directory listings, file contents, hashes, diffs, and operation results are reported only from observed file evidence.",
        ),
        recovery_notes=(
            "If the target path or folder is missing, ask for the smallest path scope needed before preparing the operation.",
            "If delete, overwrite, move, rename, chmod, or irreversible cleanup is requested, require an explicit confirmation gate.",
            "If the request is file conversion, deck/PDF export, or attachment delivery, route to materials-package or deliverable-package instead.",
        ),
    ),
    _feature_surface_skill(
        "command-operator",
        "Hermes command operator workflow: scope terminal, shell, CLI, package-manager, and test commands with cwd, environment, safety, and result-evidence gates.",
        (
            "command-operator",
            "command operator",
            "terminal command",
            "terminal task",
            "shell command",
            "shell task",
            "cli command",
            "command execution",
            "run command",
            "run this command",
            "execute command",
            "execute this command",
            "run npm test",
            "run tests",
            "npm test",
            "pnpm test",
            "bun test",
            "uv run",
            "python -m unittest",
            "pytest",
            "make test",
            "cargo test",
            "go test",
            "summarize command output",
            "터미널 명령",
            "터미널에서",
            "셸 명령",
            "쉘 명령",
            "명령 실행",
            "명령어 실행",
            "실행 준비",
            "npm test 실행",
            "테스트 실행",
            "결과 요약",
        ),
        "Use when Hermes should prepare or supervise terminal/CLI command execution without claiming the command ran or succeeded.",
        category="command",
        phase="command-task",
        next_action="prepare_command_operator_card",
        boundary="A command operator card is not terminal launch, shell execution, package-manager action, test run, stdout/stderr capture, exit-code success, filesystem mutation, network access, or destructive command evidence unless observed command-result evidence records it.",
        good_prompt="command-operator run npm test in the project terminal and summarize the output.",
        bad_prompt="command-operator run rm -rf without cwd, confirmation, or observation gates.",
        expected_outputs=(
            "command_task_card/v1",
            "command_scope/v1",
            "command_safety_gate/v1",
            "command_result_manifest/v1 when observed",
            "next action",
            "prepared-vs-observed boundary",
        ),
        artifact_expectations=(
            "command_task_card/v1 metadata-only wrapper card when prepared",
            "command_scope/v1 with command text, working directory, environment assumptions, timeout, and stop condition",
            "command_safety_gate/v1 separating read-only, write/mutation, network, credential, and destructive-risk commands",
            "command_result_manifest/v1 only when exit code, stdout/stderr, logs, or terminal transcript are observed",
        ),
        final_checklist=(
            "Command text, working directory, environment assumptions, timeout, safety level, and stop condition are explicit.",
            "Destructive, credential, network, filesystem mutation, install, deploy, and production commands are gated or marked missing.",
            "Exit codes, stdout/stderr, test results, package-manager effects, and filesystem mutations are reported only from observed command evidence.",
        ),
        recovery_notes=(
            "If command text or working directory is missing, ask for the smallest missing scope needed before preparing the command task.",
            "If the command is destructive, credentialed, networked, install/deploy-oriented, or production-affecting, require an explicit confirmation gate.",
            "If the user supplied failed command output and asks for root cause, route to build-failure-triage or agent-debug instead of preparing a fresh command.",
        ),
    ),
    _feature_surface_skill(
        "connector-operator",
        "Hermes connector operator workflow: scope external app actions across email, Slack, Discord, Notion, Linear, Jira, CRM, and similar providers with auth, payload, confirmation, and result-evidence gates.",
        (
            "connector-operator",
            "connector operator",
            "external app action",
            "external connector action",
            "saas action",
            "api action",
            "send email",
            "email customer",
            "gmail draft",
            "gmail send",
            "create linear ticket",
            "create linear issue",
            "linear ticket",
            "linear issue",
            "update linear",
            "jira ticket",
            "jira issue",
            "create jira issue",
            "open jira ticket",
            "create jira",
            "notion page",
            "update notion",
            "crm update",
            "salesforce update",
            "hubspot update",
            "create calendar event",
            "calendar invite",
            "google calendar",
            "send slack dm",
            "slack dm",
            "discord dm",
            "post to discord",
            "post to slack",
            "discord post",
            "slack post",
            "connector action",
            "이메일 보내",
            "이메일 발송",
            "메일 보내",
            "gmail 초안",
            "linear ticket",
            "linear 티켓",
            "linear 이슈",
            "jira 티켓",
            "jira 이슈",
            "notion 페이지",
            "노션 페이지",
            "캘린더 초대",
            "외부 앱",
            "외부 커넥터",
            "커넥터 액션",
        ),
        "Use when Hermes should prepare or supervise a provider-backed external app action without claiming connector availability, credentials, API mutation, delivery, or success.",
        category="connector",
        phase="connector-task",
        next_action="prepare_connector_operator_card",
        boundary="A connector operator card is not connector availability, credential validation, API call, message send, ticket creation, ticket update, database/CRM mutation, external write, webhook delivery, or provider success evidence unless observed connector-result evidence records it.",
        good_prompt="connector-operator draft an email to the customer and prepare a confirmation gate before sending.",
        bad_prompt="connector-operator send the Jira update with hidden credentials and claim it was delivered.",
        expected_outputs=(
            "connector_task_card/v1",
            "connector_scope/v1",
            "connector_auth_boundary/v1",
            "connector_confirmation_gate/v1 when mutating or sending",
            "connector_result_manifest/v1 when observed",
            "next action",
            "prepared-vs-observed boundary",
        ),
        artifact_expectations=(
            "connector_task_card/v1 metadata-only wrapper card when prepared",
            "connector_scope/v1 with provider, target object, allowed action, payload summary, and stop condition",
            "connector_auth_boundary/v1 separating missing connector, missing credentials, user-supplied authority, and credential-use prohibition",
            "connector_confirmation_gate/v1 for sending, ticket mutation, external write, webhook delivery, CRM/database update, or irreversible provider action",
            "connector_result_manifest/v1 only when provider response, message id, ticket id, API transcript, or delivery receipt is observed",
        ),
        final_checklist=(
            "Provider, target object, allowed action, payload summary, authority, confirmation policy, and stop condition are explicit.",
            "Credentials, missing connector setup, external writes, sends, ticket mutations, calendar invites, CRM updates, and webhook delivery are gated or marked missing.",
            "Message ids, ticket ids, provider responses, delivery receipts, and API effects are reported only from observed connector evidence.",
        ),
        recovery_notes=(
            "If the connector, credentials, or permission is missing, route to toolbelt-readiness before preparing action success claims.",
            "If the request is only chat thread delivery policy for Discord, Slack, or Telegram, route to gateway-intent-card instead.",
            "If the external app action would create, send, invite, mutate, or delete provider state, require an explicit confirmation gate.",
        ),
    ),
    _feature_surface_skill(
        "live-info-operator",
        "Hermes live information workflow: scope read-only weather, finance, sports, map, place, exchange-rate, and time-zone lookups with provider, freshness, units, source-quality, and result-evidence gates.",
        (
            "live-info-operator",
            "live info operator",
            "live information",
            "real time information",
            "real-time information",
            "weather today",
            "current weather",
            "weather forecast",
            "stock price",
            "crypto price",
            "btc price",
            "exchange rate",
            "sports score",
            "game score",
            "time zone",
            "timezone",
            "time in",
            "map directions",
            "directions to",
            "near me",
            "nearby restaurants",
            "traffic now",
            "오늘 날씨",
            "현재 날씨",
            "날씨 예보",
            "주가",
            "코인 가격",
            "환율",
            "스포츠 점수",
            "경기 결과",
            "시간대",
            "현재 시간",
            "지도",
            "길찾기",
            "주변 식당",
        ),
        "Use when Hermes should prepare or supervise read-only live information lookups without claiming provider availability, API access, freshness, retrieval, or result correctness.",
        category="live-info",
        phase="live-info-task",
        next_action="prepare_live_info_operator_card",
        boundary="A live information card is not provider availability, API access, live data retrieval, weather, market price, sports score, exchange-rate, time-zone, map, or place-result evidence unless observed live-info result evidence records it.",
        good_prompt="live-info-operator check today's Seoul weather with freshness, units, and provider boundaries before answering.",
        bad_prompt="live-info-operator invent the latest stock price without provider evidence or timestamp.",
        expected_outputs=(
            "live_info_task_card/v1",
            "live_info_scope/v1",
            "freshness_boundary/v1",
            "live_info_result_manifest/v1 when observed",
            "next action",
            "prepared-vs-observed boundary",
        ),
        artifact_expectations=(
            "live_info_task_card/v1 metadata-only wrapper card when prepared",
            "live_info_scope/v1 with domain, location or symbol, time window, provider preference, units, and stop condition",
            "freshness_boundary/v1 separating requested recency, provider timestamp, source quality, and stale-result handling",
            "live_info_result_manifest/v1 only when provider response, timestamp, quote/source id, or rendered result is observed",
        ),
        final_checklist=(
            "Domain, location or symbol, time window, provider preference, freshness, units, and stop condition are explicit.",
            "Provider setup, API access, source quality, stale data, and missing location/symbol decisions are gated or marked missing.",
            "Weather, price, score, exchange-rate, time-zone, map, place, and traffic facts are reported only from observed provider evidence.",
        ),
        recovery_notes=(
            "If the provider, plugin, API key, or connector is missing, route to toolbelt-readiness before preparing result claims.",
            "If the request asks for citations, best practices, docs, or broad current-source synthesis, route to web-research instead.",
            "If the request would create, update, invite, send, or mutate external provider state, route to connector-operator instead.",
        ),
    ),
    _feature_surface_skill(
        "external-connector-readiness",
        "Hermes external connector readiness workflow: decide whether a candidate plugin, connector, API, data provider, or multimodal route is safe, affordable, fresh, and observable enough to adopt, route, or trial.",
        (
            "external-connector-readiness",
            "external connector readiness",
            "connector readiness matrix",
            "plugin readiness matrix",
            "provider readiness",
            "api readiness",
            "connector adoption",
            "external plugin adoption",
            "weather plugin readiness",
            "weather connector readiness",
            "wxtrain readiness",
            "onequery read-only sql",
            "read-only sql connector",
            "sql connector readiness",
            "nextcloud connector",
            "microsoft workspace connector",
            "microsoft graph connector",
            "chainlink connector",
            "solana connector",
            "monero gateway",
            "xmr gateway",
            "private crypto transaction",
            "private cryptocurrency connector",
            "crypto transaction plugin",
            "blockchain gateway",
            "composio connector",
            "composio universal cli",
            "universal cli connector",
            "universal cli skill adoption",
            "skill connector adoption",
            "connector auth risk",
            "connector cost auth risk",
            "agentchat connector",
            "peer-to-peer agent messaging connector",
            "websocket identity connector",
            "websocket connector trial",
            "clawsocial connector",
            "social discovery connector",
            "windy pairing",
            "windymail mailbox connector",
            "matrix chat identity",
            "antigravity cli connector",
            "agy cli bridge",
            "agy bridge connector",
            "macos keychain oauth connector",
            "oracle oci connector",
            "oracle genai connector",
            "miniverse bridge",
            "crustocean platform connector",
            "cost-aware connector",
            "multimodal connector",
            "multimodal routing",
            "screenshot connector",
            "audio connector",
            "video connector",
            "video generation",
            "generate a video",
            "product demo video",
            "text to video",
            "home assistant connector",
            "home assistant integration",
            "home assistant device control",
            "home assistant smart home",
            "smart home connector",
            "device control connector",
            "plugin auto-routing",
            "connector auto-routing",
            "external tool trial",
            "커넥터 준비도",
            "외부 커넥터 준비",
            "외부 플러그인 채택",
            "플러그인 준비도",
            "커넥터 도입",
            "플러그인 도입",
            "비용 인증 리스크",
            "인증 리스크",
            "도입 비용",
            "비용 기준 커넥터",
            "자동 라우팅",
            "멀티모달 커넥터",
            "멀티모달 라우팅",
            "영상 생성",
            "제품 데모 영상",
            "홈 어시스턴트 커넥터",
            "홈 어시스턴트 연동",
            "홈 어시스턴트 기기 제어",
            "홈 어시스턴트 스마트홈",
            "홈어시스턴트 커넥터",
            "홈어시스턴트 연동",
            "홈어시스턴트 기기 제어",
            "홈어시스턴트 스마트홈",
            "스마트홈 커넥터",
        ),
        "Use before adopting, enabling, or routing an external plugin/connector/API when Hermes must compare capability, auth, cost, modality, freshness, safety, fallback, and observable trial evidence.",
        category="connector",
        phase="connector-readiness",
        next_action="prepare_external_connector_readiness",
        boundary="An external connector readiness card is not connector installation, credential validation, provider access, API invocation, multimodal capture, live-data retrieval, external mutation, cost authorization, or successful trial evidence unless observed connector-trial evidence records it.",
        good_prompt="external-connector-readiness compare weather plugin and wxtrain candidates with cost, freshness, multimodal evidence, and fallback routes before adoption.",
        bad_prompt="external-connector-readiness silently enable a paid connector and claim weather, SQL, and screenshot results without observed provider evidence.",
        expected_outputs=(
            "external_connector_readiness_card/v1",
            "connector_capability_matrix/v1",
            "auth_cost_boundary/v1",
            "live_data_freshness_policy/v1 when live data is required",
            "multimodal_routing_policy/v1 when screenshots, audio, video, or files are involved",
            "fallback_route_policy/v1",
            "connector_trial_manifest/v1 when observed",
            "next action",
            "prepared-vs-observed boundary",
        ),
        artifact_expectations=(
            "external_connector_readiness_card/v1 metadata-only wrapper card when prepared",
            "connector_capability_matrix/v1 with candidate, domain, read/write shape, modality, owner workflow, and fallback route",
            "auth_cost_boundary/v1 separating missing connector, missing credentials, paid/provider cost risk, quota, and user authority",
            "live_data_freshness_policy/v1 for requested recency, provider timestamp, stale-result handling, and source-quality thresholds",
            "multimodal_routing_policy/v1 for screenshot, audio, video, file, OCR, or visual QA evidence routes when needed",
            "connector_trial_manifest/v1 only when a provider response, capture id, query transcript, message id, or tool-call observation is recorded",
        ),
        final_checklist=(
            "Candidate connector, target domain, read/write scope, modality needs, provider owner, fallback workflow, and stop condition are explicit.",
            "Cost, quota, credential, permission, live-data freshness, multimodal capture, safety, and compliance boundaries are marked ready, missing, risky, or not_observed.",
            "Route live read-only lookups to live-info-operator, external writes to connector-operator, datasets/SQL to data-analysis, and missing tools to toolbelt-readiness before claiming results.",
            "Provider responses, screenshots, audio/video/file captures, query outputs, message ids, and external mutations are reported only from observed trial evidence.",
        ),
        recovery_notes=(
            "If the candidate list is unknown, route to skill-scout or source-finder before readiness scoring.",
            "If credentials, cost authority, or connector installation is missing, keep readiness blocked and route setup to toolbelt-readiness.",
            "If a specific provider action is already selected, route read-only live data to live-info-operator or write/mutation tasks to connector-operator.",
        ),
    ),
    _feature_surface_skill(
        "prompt-import-readiness",
        "Hermes prompt import readiness workflow: decide whether external CLI-agent prompt files can be safely reviewed, normalized, and offered as Hermes slash-command candidates without mutating prompts or command registries.",
        (
            "prompt-import-readiness",
            "prompt import readiness",
            "slash prompt import",
            "slash prompts import",
            "slash command prompt import",
            "prompt library import",
            "prompt folder import",
            "prompt directory import",
            "import CLI prompts",
            "import agent prompts",
            "CLI agent prompt files",
            "OpenCode prompt import",
            "Claude Code prompt import",
            "Codex prompt import",
            "codex prompt import",
            "Gemini CLI prompt import",
            "frontmatter prompt import",
            "prompt compatibility audit",
            "explicit prompt file audit",
            "argument interpolation",
            "$ARGUMENTS mapping",
            "{{args}} mapping",
            "$1-$9 prompt arguments",
            "prompt slash command collision",
            "Hermes slash prompts",
            "슬래시 프롬프트 가져오기",
            "프롬프트 가져오기",
            "프롬프트 디렉터리 가져오기",
            "프롬프트 폴더 가져오기",
            "슬래시 명령 프롬프트",
            "프롬프트 인자 매핑",
        ),
        "Use before importing, normalizing, or exposing external prompt files as Hermes slash commands so source trust, formats, argument interpolation, name collisions, review status, and dry-run evidence stay explicit.",
        category="prompt",
        phase="prompt-import-readiness",
        next_action="prepare_prompt_import_readiness",
        boundary="An explicit-path prompt compatibility audit observes only bounded local file classification and metadata. It is not source-directory discovery, prompt import, slash command registration, prompt mutation, command activation, imported prompt trust, or successful dry-run evidence.",
        good_prompt="prompt-import-readiness review Codex and Claude Code prompt folders before exposing them as Hermes slash commands with $ARGUMENTS mapping.",
        bad_prompt="prompt-import-readiness silently import every external prompt, overwrite slash commands, and claim the prompts are trusted without review.",
        expected_outputs=(
            "prompt_import_readiness_card/v1",
            "prompt_compatibility_audit/v1 for explicitly named local files",
            "prompt_source_inventory/v1",
            "prompt_format_matrix/v1",
            "argument_interpolation_policy/v1",
            "slash_command_collision_report/v1",
            "prompt_trust_review/v1",
            "prompt_import_manifest/v1 when observed",
            "next action",
            "prepared-vs-observed boundary",
        ),
        artifact_expectations=(
            "prompt_import_readiness_card/v1 metadata-only wrapper card when prepared",
            "prompt_compatibility_audit/v1 with bounded source metadata, format classification, argument syntax, collisions, and review reasons for explicitly named local files",
            "prompt_source_inventory/v1 with source directory, agent family, file count, format claim, and review state",
            "prompt_format_matrix/v1 separating YAML frontmatter, TOML frontmatter, raw markdown/text, and unsupported formats",
            "argument_interpolation_policy/v1 for $ARGUMENTS, $1-$9, {{args}}, named placeholders, escaping, and missing argument handling",
            "slash_command_collision_report/v1 with command names, aliases, existing Hermes commands, and conflict resolution policy",
            "prompt_trust_review/v1 with source trust, prompt-injection risk, secret leakage risk, license/source notes, and review owner",
            "prompt_import_manifest/v1 only when file reads, parsed prompts, generated slash-command candidates, or dry-run output are observed",
        ),
        final_checklist=(
            "Prompt sources, agent family, expected file formats, argument syntax, slash-command names, trust level, and stop condition are explicit.",
            "Explicit-path audit reads and compatibility results are observed only in their audit output; source discovery, command registration, prompt mutation, slash-command activation, and dry-run execution remain marked not_observed.",
            "Route broad candidate discovery to skill-scout, prompt/tool safety to security-safety-review, missing CLIs or directories to toolbelt-readiness, and approved implementation to a selected executor handoff.",
            "Imported prompts, generated command files, registry updates, and dry-run results are reported only from observed prompt-import evidence.",
        ),
        recovery_notes=(
            "If source prompt directories are unknown, route to workspace-audit or skill-scout before readiness scoring.",
            "If source trust, prompt-injection risk, secrets, or destructive command content is unclear, route to security-safety-review before import.",
            "If the user asks to actually copy, generate, or register prompt files, prepare an executor or workspace-file handoff and keep readiness prepared_not_observed until file evidence exists.",
        ),
    ),
    _feature_surface_skill(
        "physical-device-readiness",
        "Hermes readiness workflow for robots, 3D printers, IoT relays, sensors, and lab hardware before hardware trials.",
        (
            "physical-device-readiness",
            "physical device readiness",
            "device safety readiness",
            "physical device safety",
            "hardware safety gate",
            "3d printer readiness",
            "3D printer safety",
            "snapmaker printer safety",
            "snapmaker readiness",
            "moonraker klipper safety",
            "camera-gated print start",
            "camera gate",
            "heat command approval",
            "iot relay safety",
            "sensor relay safety",
            "robotics safety",
            "robot control readiness",
            "vla robot readiness",
            "mushroom cultivation relay safety",
            "raspberry pi relay safety",
            "물리 장비 안전",
            "하드웨어 안전",
            "3d 프린터 안전",
            "프린터 안전",
            "로봇 제어 준비",
            "iot 릴레이 안전",
            "센서 릴레이 안전",
        ),
        "Use before preparing or adopting a workflow that could move, heat, print, actuate, unlock, or otherwise affect physical devices so safety envelope, sensor/camera gates, dry-run policy, operator approval, emergency stop, and observation requirements are explicit.",
        category="operations",
        phase="device-readiness",
        next_action="prepare_physical_device_readiness",
        boundary="A physical device readiness card is not device discovery, network pairing, credential validation, slicer output, G-code safety, camera inspection, sensor reading, relay actuation, robot movement, heat command, print start, emergency stop test, or successful hardware trial evidence unless observed device-trial evidence records it.",
        good_prompt="physical-device-readiness check Snapmaker printer safety with camera gate, slicer dry-run, heat command approval, and emergency-stop evidence before printing.",
        bad_prompt="physical-device-readiness start the printer, heat the bed, flip relays, and claim the robot is safe without observed operator approval or device telemetry.",
        expected_outputs=(
            "physical_device_readiness_card/v1",
            "device_safety_envelope/v1",
            "hazard_and_actuator_inventory/v1",
            "sensor_camera_gate_policy/v1",
            "operator_approval_policy/v1",
            "dry_run_and_simulation_policy/v1",
            "emergency_stop_and_rollback_plan/v1",
            "device_trial_manifest/v1 when observed",
            "next action",
            "prepared-vs-observed boundary",
        ),
        artifact_expectations=(
            "physical_device_readiness_card/v1 metadata-only wrapper card when prepared",
            "device_safety_envelope/v1 with device, workspace, hazards, actuator classes, human/property risk, owner, authority, and stop condition",
            "hazard_and_actuator_inventory/v1 separating motion, heat, pressure, electrical, relay, network, credential, and environmental risks",
            "sensor_camera_gate_policy/v1 for camera/OCR, sensor telemetry, stale readings, manual inspection, and blocked/no-camera fallback",
            "operator_approval_policy/v1 with explicit human authority, confirmation moment, disallowed autonomous actions, and emergency contact or stop owner",
            "dry_run_and_simulation_policy/v1 for slicer/G-code dry-runs, command previews, mock relays, simulated robot paths, and no-hardware trial mode",
            "emergency_stop_and_rollback_plan/v1 with stop command, power/network isolation, recovery boundary, and abort condition",
            "device_trial_manifest/v1 only when real telemetry, camera capture id, dry-run output, command transcript, operator confirmation, or hardware observation is recorded",
        ),
        final_checklist=(
            "Device scope, actuator and hazard classes, sensor/camera gates, operator approval, dry-run policy, emergency stop, and stop condition are explicit.",
            "Physical actions, heat commands, relay toggles, robot movement, print starts, camera inspections, and telemetry readings are marked observed, missing, risky, or not_observed.",
            "Route external APIs or provider setup to external-connector-readiness, terminal commands to command-operator, safety concerns to security-safety-review, visual/camera checks to visual-qa, and missing tools to toolbelt-readiness.",
            "Do not claim device movement, heat, print, relay, robot, camera, sensor, or emergency-stop success without observed device-trial evidence.",
        ),
        recovery_notes=(
            "If the device, workspace, actuator, or authority is unclear, keep readiness blocked until the missing safety context is named.",
            "If the user asks to execute commands, move hardware, heat a bed/nozzle, flip a relay, or start a print, route to command-operator or connector-operator and require observed operator approval before any execution claim.",
            "If camera or telemetry evidence is required but unavailable, route to visual-qa or toolbelt-readiness and keep the physical device readiness card prepared_not_observed.",
        ),
    ),
    _feature_surface_skill(
        "content-operator",
        "Hermes content operator workflow: scope publish-ready writing, rewriting, summarization, translation, release-note, newsletter, customer-copy, social-copy, README-copy, and email-draft work with audience, tone, style, source, review, and hallucination gates.",
        (
            "content-operator",
            "content operator",
            "content workflow",
            "writing workflow",
            "publish-ready writing",
            "publish ready writing",
            "release notes",
            "release note draft",
            "newsletter draft",
            "customer announcement",
            "customer copy",
            "product copy",
            "landing page copy",
            "social post draft",
            "email draft",
            "draft an email",
            "rewrite for executives",
            "summarize for customers",
            "style guide rewrite",
            "audience and tone",
            "tone of voice",
            "콘텐츠 오퍼레이터",
            "글쓰기 워크플로",
            "릴리즈 노트",
            "릴리즈노트",
            "뉴스레터 초안",
            "고객 공지문",
            "고객 공지",
            "고객용 요약",
            "메일 초안",
            "이메일 초안",
            "채널별 톤",
            "문체 가이드",
        ),
        "Use when Hermes should prepare or supervise quality-controlled content creation or transformation without claiming source access, fact verification, stakeholder approval, publishing, sending, file export, or delivery.",
        category="content",
        phase="content-task",
        next_action="prepare_content_operator_card",
        boundary="A content operator card is not source retrieval, fact verification, hallucination-free copy, stakeholder approval, publishing, email/message sending, file export, delivery, or proof that final copy was accepted unless observed content output evidence records it.",
        good_prompt="content-operator draft publish-ready release notes with audience, tone, source scope, review gates, and hallucination checks.",
        bad_prompt="content-operator invent missing facts and claim the customer announcement was sent.",
        expected_outputs=(
            "content_task_card/v1",
            "source_scope/v1",
            "audience_tone_style/v1",
            "content_review_gate/v1",
            "content_output_manifest/v1 when observed",
            "next action",
            "prepared-vs-observed boundary",
        ),
        artifact_expectations=(
            "content_task_card/v1 metadata-only wrapper card when prepared",
            "source_scope/v1 with supplied sources, missing sources, fact-risk, citation need, and no-invention rule",
            "audience_tone_style/v1 with audience, channel, language, tone, style guide, length, format, and accessibility constraints",
            "content_review_gate/v1 separating draft, reviewer approval, legal/compliance needs, publish/send/file-export authority, and stop condition",
            "content_output_manifest/v1 only when produced draft, revision diff, approval, export, publish, or delivery evidence is observed",
        ),
        final_checklist=(
            "Audience, channel, language, tone, style guide, length, source scope, fact-risk, review owner, and stop condition are explicit.",
            "Missing facts, source gaps, claims needing citations, legal/compliance needs, approval, publish/send authority, and file-export needs are gated or marked missing.",
            "Published, sent, exported, approved, and fact-verified claims are reported only from observed evidence.",
        ),
        recovery_notes=(
            "If the request asks for citations, current facts, or source-backed evidence gathering, route to web-research or source-finder before drafting.",
            "If the request asks to send, post, invite, ticket, or mutate an external app, route to connector-operator before claiming delivery.",
            "If the request asks for PDF, PPT, DOCX, HWP, spreadsheet, or attachment packaging, route to materials-package or deliverable-package.",
            "If the request is a simple one-off sentence or paragraph transformation, answer directly instead of opening a workflow.",
        ),
    ),
    _feature_surface_skill(
        "media-input-operator",
        "Hermes media input workflow: scope audio, video, YouTube, screenshot, receipt image, OCR, meeting recording, transcript, timestamp, and clip-summary requests with source, permission, extraction, transcription, and hallucination gates.",
        (
            "media-input-operator",
            "media input operator",
            "media input",
            "audio transcription",
            "audio transcript",
            "transcribe audio",
            "transcribe this audio",
            "meeting recording",
            "recording transcript",
            "video transcript",
            "youtube summary",
            "youtube video",
            "summarize youtube",
            "summarize this youtube",
            "video summary",
            "summarize this video",
            "ocr image",
            "image ocr",
            "photo ocr",
            "picture ocr",
            "graphic ocr",
            "screenshot ocr",
            "ocr this image",
            "ocr receipt image",
            "ocr this receipt image",
            "receipt ocr",
            "receipt image ocr",
            "receipt text",
            "receipt text from image",
            "receipt fields",
            "receipt fields from image",
            "receipt image extraction",
            "receipt image text",
            "receipt image fields",
            "parse receipt image",
            "receipt image parse",
            "receipt image into fields",
            "image text extraction",
            "extract text from image",
            "extract text from this image",
            "screenshot text extraction",
            "extract text from screenshot",
            "extract text from this screenshot",
            "screenshot to text",
            "timestamps",
            "with timestamps",
            "clip summary",
            "podcast summary",
            "webinar summary",
            "오디오 전사",
            "음성 전사",
            "회의 녹음",
            "녹음 요약",
            "영상 요약",
            "유튜브 요약",
            "youtube 요약",
            "이미지 ocr",
            "이미지 OCR",
            "이미지 텍스트 추출",
            "이미지에서 텍스트 추출",
            "영수증 ocr",
            "영수증 OCR",
            "영수증 이미지 ocr",
            "영수증 이미지 OCR",
            "스크린샷 텍스트 추출",
            "스크린샷에서 텍스트 추출",
            "타임스탬프",
            "타임라인 요약",
        ),
        "Use when Hermes should prepare or supervise audio/video transcript, YouTube/video summary, OCR, screenshot text extraction, receipt image parsing, or timestamped media extraction work without claiming media access, download, transcription, OCR output, or factual summary evidence.",
        category="media",
        phase="media-input-task",
        next_action="prepare_media_input_card",
        boundary="A media input card is not media access, file upload, download, transcript extraction, OCR output, screenshot text extraction, receipt fields, speech-to-text output, timestamp accuracy, copyright clearance, source retrieval, or summary correctness evidence unless observed media-result evidence records it.",
        good_prompt="media-input-operator transcribe this audio meeting and summarize action items with evidence and timestamp boundaries.",
        bad_prompt="media-input-operator invent a YouTube transcript and claim the timestamps are verified without media evidence.",
        expected_outputs=(
            "media_input_task_card/v1",
            "media_source_scope/v1",
            "transcript_boundary/v1",
            "media_summary_plan/v1",
            "media_result_manifest/v1 when observed",
            "next action",
            "prepared-vs-observed boundary",
        ),
        artifact_expectations=(
            "media_input_task_card/v1 metadata-only wrapper card when prepared",
            "media_source_scope/v1 with media type, source location, permission boundary, requested time range, and stop condition",
            "transcript_boundary/v1 separating supplied transcript, missing transcript, ASR/extraction requirement, language, speaker labels, and confidence gaps",
            "media_summary_plan/v1 naming action-item, timestamped, clip, chapter, quote, or evidence-linked summary method",
            "media_result_manifest/v1 only when supplied transcript, media file metadata, provider response, or observed transcript output exists",
        ),
        final_checklist=(
            "Media type, source location, permission boundary, transcript availability, language, requested output, timestamp requirement, and stop condition are explicit.",
            "Downloads, uploads, ASR, transcript extraction, speaker labels, copyrighted media access, and provider setup are gated or marked missing.",
            "Transcript text, OCR output, screenshot text, receipt fields, timestamps, quotes, action items, and media-summary claims are reported only from observed media or supplied transcript/extraction evidence.",
        ),
        recovery_notes=(
            "If the media or transcript is missing, ask for the smallest source, file, transcript, or provider result needed.",
            "If the request is broad current-source research about a video topic, route to web-research or source-finder before summary.",
            "If the user wants a PPT/PDF/report generated from the media summary, route to materials-package after media input evidence is clear.",
        ),
    ),
    _feature_surface_skill(
        "data-analysis",
        "Hermes data analysis workflow: scope supplied data with provenance, causal-claim, and hallucination guards.",
        (
            "data-analysis",
            "data analysis",
            "dataset analysis",
            "csv analysis",
            "json analysis",
            "log analysis",
            "table analysis",
            "analyze csv",
            "analyze this csv",
            "analyze json",
            "analyze logs",
            "summarize anomalies",
            "anomaly analysis",
            "trend analysis",
            "segment analysis",
            "column analysis",
            "schema check",
            "table to chart",
            "chart with an executive summary",
            "spreadsheet delta analysis",
            "cohort analysis",
            "retention analysis",
            "correlation analysis",
            "causal analysis",
            "causality check",
            "데이터 분석",
            "csv 분석",
            "json 분석",
            "로그 분석",
            "이상치 분석",
            "추세 분석",
            "오류 패턴",
            "컬럼 분석",
            "전환율 델타",
            "차트 요약",
            "상관관계 분석",
            "인과 분석",
            "인과관계",
        ),
        "Use when Hermes should prepare supplied structured, unstructured, or mixed data analysis without unsupported numeric or causal claims.",
        category="analysis",
        phase="data-task",
        next_action="prepare_data_analysis_card",
        boundary="A data analysis card is not file extraction, query execution, chart generation, statistical proof, data correctness, hallucination-safe numeric evidence, association, or causality unless observed data and method evidence records it.",
        good_prompt="data-analysis analyze this CSV and summarize anomalies by segment.",
        bad_prompt="data-analysis invent trends from an unavailable spreadsheet.",
        expected_outputs=(
            "data_analysis_task_card/v1",
            "dataset_scope/v1",
            "analysis_method_plan/v1",
            "operations_data_harness/v1",
            "product_evidence_loop/v1",
            "analysis_result_summary/v1 when observed",
            "next action",
            "prepared-vs-observed boundary",
        ),
        artifact_expectations=(
            "data_analysis_task_card/v1 metadata-only wrapper card when prepared",
            "dataset_scope/v1 with source, row/record scope, columns or schema, filters, and stop condition",
            "analysis_method_plan/v1 naming summary, anomaly, trend, segment, schema, or log-pattern methods",
            "operations_data_harness/v1 for relationship and causal boundaries",
            "product_evidence_loop/v1 for prepared opaque data reference metadata",
            "analysis_result_summary/v1 only from observed data, calculations, query output, or supplied evidence",
        ),
        final_checklist=(
            "Dataset or corpus source, record scope, schema or extraction method, join assumptions, analysis question, method, and stop condition are explicit.",
            "Numeric claims, anomalies, trends, segments, and log patterns are reported only from observed data or supplied evidence.",
            "Causal claims require observed identification evidence.",
            "Source acquisition, file conversion, report generation, and code fixes are routed to the narrower workflow when stronger.",
        ),
        recovery_notes=(
            "If the data itself is missing, ask for the smallest dataset sample, schema, or query output needed.",
            "If the user wants datasets found online, route to source-finder before analysis.",
            "If the user wants a PPT/PDF/XLSX report generated from data, route to materials-package or deliverable-package after analysis scope is clear.",
        ),
    ),
    _feature_surface_skill(
        "toolbelt-readiness",
        "Hermes toolbelt readiness workflow: check which MCP servers, CLIs, APIs, credentials, and connectors a workflow needs before claiming it can run.",
        (
            "toolbelt-readiness",
            "mcp readiness",
            "tool readiness",
            "plugin readiness",
            "connector readiness",
            "needed mcp",
            "api credential",
            "missing cli",
            "missing plugin",
            "missing connector",
            "external connector",
            "external tool",
            "mcp server",
            "mcp servers",
            "mcp tool",
            "mcp tools",
            "toolbelt",
            "github cli",
            "linear cli",
            "jira cli",
            "notion connector",
            "google drive connector",
            "gmail connector",
            "slack api",
            "browser tool",
            "image generator connector",
            "외부 도구",
            "외부 연결",
            "mcp",
            "커넥터",
            "플러그인",
            "자격증명",
            "credential",
        ),
        "Use when a workflow depends on MCP, CLI, API credentials, or connectors and Hermes must show installed, missing, optional, and unsafe tools.",
        category="tools",
        phase="readiness-check",
        next_action="prepare_toolbelt_readiness",
        boundary="A toolbelt readiness card is not MCP server installation, credential validation, API access, connector invocation, or successful workflow execution evidence.",
        good_prompt="toolbelt-readiness what MCP or CLI tools do I need for weekly Linear and GitHub triage?",
        bad_prompt="toolbelt-readiness claim Gmail access works without an observed credential check.",
    ),
    _feature_surface_skill(
        "harness-session-inventory",
        "Hermes harness session inventory workflow: normalize Codex, Claude Code, Hermes, OpenCode, Cursor, MCP host, worktree, and wrapper session metadata into one drift-aware inventory.",
        (
            "harness-session-inventory",
            "harness session inventory",
            "session inventory",
            "session adapter",
            "session adapters",
            "harness sessions",
            "mcp inventory",
            "mcp config inventory",
            "mcp drift",
            "harness drift",
            "connector drift",
            "worktree inventory",
            "worktree lifecycle",
            "operator inventory",
            "control pane inventory",
            "codex session inventory",
            "claude code session inventory",
            "find previous coding session",
            "recover coding session",
            "previous codex coding session",
            "coding session recall",
            "세션 인벤토리",
            "지난 코딩 세션",
            "코딩 세션 복구",
            "세션 기억 복구",
            "하네스 세션",
            "하네스 드리프트",
            "MCP 인벤토리",
            "MCP 설정 드리프트",
            "워크트리 인벤토리",
            "커넥터 드리프트",
        ),
        "Use when operators need a cross-harness/session/MCP/worktree inventory and drift summary before claiming any host loaded, connector ran, or agent session progressed.",
        category="observability",
        phase="harness-session-inventory",
        next_action="prepare_harness_session_inventory",
        boundary="A harness session inventory is not host load, MCP tool-call, connector availability, executor dispatch, worktree cleanup, merge-conflict resolution, or session progress evidence.",
        good_prompt="harness-session-inventory compare Codex, Claude Code, Hermes, MCP configs, and worktrees for drift before we dispatch agents.",
        bad_prompt="harness-session-inventory claim every MCP host loaded and every agent session is healthy from config files alone.",
        expected_outputs=(
            "harness_session_inventory/v1 card or guidance",
            "harness_session_adapter_matrix/v1",
            "mcp_inventory_drift_report/v1",
            "worktree_lifecycle_snapshot/v1",
            "session_progress_slots/v1",
            "next action",
            "prepared-vs-observed boundary",
        ),
        artifact_expectations=(
            "harness_session_inventory/v1 metadata-only runtime or wrapper card when recorded",
            "harness_session_adapter_matrix/v1 with observed, prepared, missing, and stale adapters",
            "mcp_inventory_drift_report/v1 with secret-redacted config/source drift only",
            "worktree_lifecycle_snapshot/v1 with merge-conflict and cleanup candidates when observed",
        ),
        final_checklist=(
            "The inventory scope names the harnesses, sessions, MCP hosts, connector configs, and worktrees being compared.",
            "Prepared, observed, missing, stale, and drifted entries are separated before any health or progress claim.",
            "The next action says whether to load a host, verify a connector, inspect a worktree, dispatch an executor, or stay blocked.",
        ),
        recovery_notes=(
            "If config sources are unavailable, report only the discovered surfaces and mark the missing hosts not_observed.",
            "If cleanup, host load, connector execution, or session progress is requested, route to the owning workflow instead of folding it into inventory.",
        ),
    ),
    _feature_surface_skill(
        "ops-observability-card",
        "Hermes ops observability workflow: prepare an operations command-board for wrapper-safe token, cost, latency, run history, queue, failure-mode, external metric-provider, and service-quality evidence boundaries.",
        (
            "ops-observability-card",
            "observability card",
            "operations command board",
            "ops command board",
            "service quality board",
            "service quality",
            "external metric provider",
            "metric provider",
            "prometheus metrics",
            "grafana metrics",
            "cost telemetry",
            "latency telemetry",
            "token telemetry",
            "run history",
            "loop telemetry",
            "failure mode",
            "monitor tokens",
            "service health",
            "slo dashboard",
            "비용",
            "토큰",
            "지연시간",
            "관측성",
            "운영 지휘판",
            "서비스 품질",
            "메트릭",
            "프로메테우스",
            "그라파나",
        ),
        "Use when automation, loops, gateway work, executor handoffs, or service operations need a safe command-board for cost, latency, token, history, failure-mode, supplied metric-provider, and service-quality visibility.",
        category="observability",
        phase="telemetry-card",
        next_action="prepare_ops_observability_card",
        boundary="An ops observability card is not billing truth, provider quota truth, live metric-provider access, complete tracing, SLO pass, incident closure, root-cause proof, remediation completion, performance proof, or successful workflow completion evidence.",
        good_prompt="ops-observability-card show token, cost, latency, supplied Prometheus/Grafana metrics, and missing service-quality evidence for this loop.",
        bad_prompt="ops-observability-card claim exact provider billing, healthy SLO, incident closure, or remediation completion from local estimates.",
        expected_outputs=(
            "ops-observability-card/v1 card or guidance",
            "external_metric_provider/v1 payload contract",
            "external_metric_provider_adapter/v1 adapter contract",
            "ops_service_quality_board/v1 service-quality board",
            "typed service-quality downgrade gaps",
            "next action",
            "prepared-vs-observed boundary",
        ),
        artifact_expectations=(
            "ops-observability-card/v1 metadata-only runtime or wrapper card when recorded",
            "external_metric_provider/v1 supplied metric payload when available",
            "external_metric_provider_adapter/v1 connector-ready adapter metadata when available",
            "ops_service_quality_board/v1 evidence-gated service-quality board",
        ),
    ),
    _feature_surface_skill(
        "achievements",
        "Hermes achievements observation workflow: summarize hermes-achievements badges, tiers, recent unlocks, and progress from local plugin artifacts.",
        (
            "achievements",
            "achievement",
            "badges",
            "badge",
            "my badges",
            "show achievements",
            "achievement summary",
            "unlocked badges",
            "badge progress",
            "achievement tier",
            "recent unlocks",
            "badge share card",
            "업적",
            "배지",
            "뱃지",
            "도전과제",
            "업적 요약",
            "実績",
            "バッジ",
            "成就",
            "徽章",
        ),
        "Use when the user asks which achievements or badges they unlocked, badge progress or tiers, recent unlocks, or wants an achievements section prepared for a report.",
        category="observability",
        phase="telemetry-card",
        next_action="show_achievements_summary",
        boundary=(
            "An achievements card reflects only locally observed hermes-achievements plugin artifacts; it is not a "
            "session-history rescan, badge recomputation, unlock proof beyond those artifacts, or productivity evidence."
        ),
        good_prompt="achievements show my unlocked badges and what is closest to the next tier.",
        bad_prompt="achievements recompute my session history and grant the missing badges.",
        expected_outputs=(
            "hermes_achievements_observation/v1 summary or badge list",
            "recent unlocks and progress hints",
            "next action",
            "prepared-vs-observed boundary",
        ),
        artifact_expectations=(
            "hermes_achievements_observation/v1 metadata-only payload from `omh achievements` when recorded",
        ),
    ),
    _feature_surface_skill(
        "agent-ops-review",
        "Hermes agent ops review workflow: help managers inspect AI-agent progress, blockers, quality gates, and throughput levers.",
        (
            "agent-ops-review",
            "agent ops review",
            "agent productivity",
            "operator productivity",
            "manager view",
            "quality dashboard",
            "throughput review",
            "agent work quality",
            "coding progress quality",
            "coding progress",
            "where is codex",
            "what's going on",
            "status update please",
            "what are you doing",
            "what are you working on",
            "where are we",
            "今何してる",
            "现在在做什么",
            "qué está pasando",
            "qu'est-ce qui se passe",
            "was ist los",
            "ai agent manager",
            "관리자 입장",
            "Codex 작업",
            "Codex 작업이 어디까지",
            "코덱스 작업",
            "작업이 어디까지",
            "진행됐는지",
            "진행되었는지",
            "처리량",
            "작업 품질",
            "진행상황",
            "무슨일이노",
            "뭔일임",
            "무슨 일이야",
            "뭐해",
            "지금 뭐 하고 있어",
            "작업상황 브리핑",
            "어디까지 됐어",
            "리서치 코딩 리뷰",
        ),
        "Use when Hermes should explain AI-agent work: quality gates, progress, blockers, next actions, and throughput.",
        category="operator",
        phase="manager-review",
        next_action="prepare_agent_ops_review",
        boundary="An agent ops review card is not source retrieval, executor dispatch, coding progress, implementation, review, verification, CI, merge, platform delivery, provider billing, or live runtime telemetry evidence. If Hermes is the coding owner, summarize `hermes_coding_harness/v1` stage, lane owner, next action, and missing evidence.",
        good_prompt="agent-ops-review show quality, blockers, and throughput for AI-agent work.",
        bad_prompt="agent-ops-review claim Codex finished and CI passed because a handoff exists.",
    ),
    _feature_surface_skill(
        "agent-debug",
        "Agent Debug workflow: capture a stuck, looping, drifting, or repeatedly failing agent run, diagnose the likely failure pattern, and prepare the smallest safe recovery action.",
        (
            "agent-debug",
            "agent debug",
            "agent debugging",
            "agent introspection",
            "agent self-debug",
            "self-debug",
            "self debugging",
            "looping agent",
            "agent loop failure",
            "agent run stuck",
            "agent failure capture",
            "tool retry loop",
            "repeated tool calls",
            "context drift",
            "prompt drift",
            "token burn",
            "에이전트 디버그",
            "에이전트 실패",
            "에이전트 반복 실패",
            "반복 실패",
            "도구 반복",
            "컨텍스트 드리프트",
            "토큰 낭비",
        ),
        "Use when an agent run is stuck, looping on tools, burning tokens without progress, drifting from the objective, losing context, or failing on recoverable environment/tool assumptions.",
        category="operations",
        phase="agent-debug",
        next_action="prepare_agent_debug",
        boundary="An agent debug report is not executor reset, hidden state mutation, tool repair, implementation, verification, CI, merge-readiness, merge, or proof that future loops are fixed. Record only observed failure evidence, diagnosis hypotheses, contained recovery actions, and remaining blockers.",
        good_prompt="agent-debug capture why this agent is looping on the same tool and prepare the smallest safe recovery action.",
        bad_prompt="agent-debug silently reset the executor, patch the environment, and claim the future loop is fixed.",
        expected_outputs=(
            "agent_debug_report/v1",
            "agent_failure_capture/v1",
            "agent_failure_pattern_hypothesis/v1",
            "contained_recovery_action/v1",
        ),
        artifact_expectations=(
            "agent_debug_report/v1 with failure pattern, recent tool sequence, goal/context pressure, environment assumptions, recovery action, and evidence status",
            "agent_failure_capture/v1 separating observed errors and tool loops from inferred root-cause hypotheses",
            "contained_recovery_action/v1 with the smallest safe next action and explicit escalation boundary",
        ),
        final_checklist=(
            "Failure state, intended goal, recent tool sequence, and context pressure are captured.",
            "Diagnosis distinguishes repeated command/tool loops, context drift, environment mismatch, service errors, and wrong-hypothesis tests.",
            "Recovery action is contained, reversible, and does not claim implementation, verification, CI, merge, or future-loop fixes.",
        ),
        recovery_notes=(
            "If the request is install/setup health, route to doctor.",
            "If the request is a manager status or throughput review, route to agent-ops-review.",
            "If the request is a durable self-improvement record after diagnosis, route to workflow-learning.",
        ),
    ),
    _feature_surface_skill(
        "failure-signal-audit",
        "Failure Signal Audit workflow: find swallowed errors, unsafe fallbacks, hidden UI/runtime failures, and missing propagation before they become false green status.",
        (
            "failure-signal-audit",
            "failure signal audit",
            "silent failure",
            "silent failures",
            "silent failure hunter",
            "swallowed error",
            "swallowed errors",
            "empty catch",
            "ignored exception",
            "hidden failure",
            "hidden failures",
            "dangerous fallback",
            "bad fallback",
            "fallback hides errors",
            "missing error propagation",
            "error propagation",
            "console errors ignored",
            "network failures ignored",
            "false green",
            "false pass",
            "무음 실패",
            "조용한 실패",
            "숨은 실패",
            "삼킨 에러",
            "에러 삼킴",
            "위험한 fallback",
            "위험한 폴백",
            "폴백이 에러 숨김",
            "실패 신호 감사",
            "실패 신호",
        ),
        "Use when Hermes should audit code, frontend/browser behavior, agent traces, or runtime reports for failures that were swallowed, downgraded, hidden by fallbacks, or reported as green without enough evidence.",
        category="review",
        phase="failure-signal-audit",
        next_action="prepare_failure_signal_audit",
        boundary="A failure signal audit is not remediation, code modification, runtime repair, console/network pass, incident closure, verification, review, CI, merge-readiness, merge, or proof that hidden failures no longer exist.",
        good_prompt="failure-signal-audit check this frontend and agent trace for swallowed errors, false green status, and dangerous fallbacks.",
        bad_prompt="failure-signal-audit silently patch every catch block and claim the system is reliable now.",
        expected_outputs=(
            "failure_signal_audit_plan/v1",
            "silent_failure_finding/v1 when observed",
            "fallback_risk_matrix/v1",
            "propagation_gap_map/v1",
            "false_green_status_review/v1",
            "remediation_handoff/v1 when needed",
        ),
        artifact_expectations=(
            "failure_signal_audit_plan/v1 with source boundary, surfaces, evidence types, and stop condition",
            "silent_failure_finding/v1 only from observed code, trace, console, network, test, or runtime evidence",
            "fallback_risk_matrix/v1 separating safe fallback, user-visible degraded mode, masked failure, and destructive fallback",
            "propagation_gap_map/v1 for missing context, lost stack, ignored async rejection, empty catch, null/empty default, or log-only handling",
            "false_green_status_review/v1 comparing PASS/green claims against observed checks and missing signals",
            "remediation_handoff/v1 only after findings are accepted and the selected owner is explicit",
        ),
        final_checklist=(
            "Audit scope, source surfaces, and evidence types are named.",
            "Swallowed errors, dangerous fallbacks, propagation gaps, and false-green claims are reported as separate finding types.",
            "Each finding names location or evidence ref, severity, user/operator impact, and a smallest safe remediation route.",
            "No remediation, runtime repair, verification, CI, merge, or future reliability claim is made without observed follow-up evidence.",
        ),
        recovery_notes=(
            "If no code/trace/runtime evidence is supplied, prepare the audit plan and request the smallest source surface to inspect.",
            "If the user wants live service SLO or incident review, route to reliability-review.",
            "If the user wants rendered browser proof, route frontend visual evidence to visual-qa before PASS.",
        ),
    ),
    _feature_surface_skill(
        "instinct-ledger",
        "Instinct Ledger workflow: turn repeated project or cross-project lessons into atomic, confidence-scored instinct candidates with scoped promotion and export boundaries.",
        (
            "instinct-ledger",
            "instinct ledger",
            "project instincts",
            "project-scoped instincts",
            "project scoped instincts",
            "global instincts",
            "instinct review",
            "instinct candidate",
            "instinct candidates",
            "instinct promotion",
            "promote instinct",
            "promote learning",
            "confidence scored learning",
            "confidence-scored learning",
            "project learning patterns",
            "cross-project learning",
            "export instincts",
            "import instincts",
            "학습 본능",
            "프로젝트별 학습",
            "프로젝트 스코프 학습",
            "전역 학습 승격",
            "학습 승격",
            "학습 패턴 승격",
        ),
        "Use when Hermes should review repeated observations, user corrections, workflow lessons, or failure patterns as atomic project-scoped or global instinct candidates with confidence, evidence, promotion, import, or export decisions.",
        category="optimization",
        phase="instinct-ledger",
        next_action="prepare_instinct_ledger",
        boundary="An instinct ledger is not hook installation, automatic observation, model training, hidden memory mutation, skill mutation, prompt mutation, global rule promotion, import, export, or proof that future behavior changed. Record only reviewed candidate instincts, confidence, scope, promotion state, and evidence gaps.",
        good_prompt="instinct-ledger turn these repeated OMH review lessons into project-scoped instincts and show which ones could be promoted globally.",
        bad_prompt="instinct-ledger silently install hooks, learn from every prompt, and mutate all skills globally.",
        expected_outputs=(
            "instinct_ledger_plan/v1",
            "instinct_candidate/v1",
            "project_instinct_scope_map/v1",
            "instinct_promotion_review/v1",
            "instinct_export_review/v1 when requested",
        ),
        artifact_expectations=(
            "instinct_candidate/v1 with trigger, action, confidence, domain, scope, source evidence, non-goals, and review state",
            "project_instinct_scope_map/v1 separating project, global, imported, and promotion-candidate instincts",
            "instinct_promotion_review/v1 with repeated evidence, confidence threshold, conflicts, and approval state",
            "instinct_export_review/v1 with redaction, destination, import/export trust gaps, and raw-observation exclusion when requested",
        ),
        final_checklist=(
            "Each instinct is atomic: one trigger, one action, one scope, confidence, evidence refs, and review state.",
            "Project-specific conventions, global practices, project/global promotion candidates, imports, and exports are separated.",
            "No hooks, memory writes, skill edits, global promotion, import/export, or behavior-change claims are made without observed approval and implementation evidence.",
        ),
        recovery_notes=(
            "If the request is a single missed route or run trace, route to workflow-learning first.",
            "If the request is to mutate durable rules, prompts, skills, or AGENTS guidance, route to rules-distill or implementation after review approval.",
            "If evidence comes from a stuck run, use agent-debug before converting lessons into instincts.",
        ),
    ),
    _feature_surface_skill(
        "skill-scout",
        "Skill Scout workflow: prepare a metadata-only search-before-creation report for local, marketplace, GitHub, and web skill candidates with risk review and adoption options.",
        (
            "skill-scout",
            "skill scout",
            "skill candidate",
            "skill candidate search",
            "skill discovery",
            "find a skill",
            "find skills",
            "top skills",
            "popular skills",
            "famous hermes skills",
            "useful hermes skills",
            "hermes skills/plugin",
            "skills/plugin",
            "agentskills.io top skills",
            "is there a skill",
            "existing skill",
            "fork a skill",
            "extend a skill",
            "create skill after search",
            "new skill search",
            "skill adoption",
            "스킬 스카우트",
            "스킬 후보",
            "스킬 찾기",
            "스킬 검색",
            "스킬 만들기 전",
            "유명한 hermes skills",
            "유명한 hermes skill",
            "유용한 hermes skills",
            "스킬 플러그인 후보",
            "플러그인 찾아",
            "플러그인 비교",
            "없는 것 설치할지 비교",
            "기존 스킬",
        ),
        "Use before creating or adapting a skill so OMH can compare existing local, marketplace, GitHub, or web candidates without installing, copying, or trusting them by default.",
        category="operations",
        phase="skill-scout",
        next_action="prepare_skill_scout",
        boundary="A skill scout report is not skill installation, external source trust, marketplace mutation, file copy, network retrieval, credential use, implementation, review, CI, or proof that a candidate is safe to adopt.",
        good_prompt="skill-scout find existing skill candidates before we create a release-note workflow skill.",
        bad_prompt="skill-scout install the best GitHub skill and copy it into the marketplace without review.",
        expected_outputs=(
            "skill_scout_query/v1",
            "local_skill_candidate_inventory/v1 when observed",
            "external_skill_candidate_risk_review/v1 when observed",
            "awesome_hermes_agent_coverage/v1 for upstream ecosystem comparison when requested",
            "skill_adoption_decision_matrix/v1",
            "skill_scout_recommendation/v1",
        ),
        artifact_expectations=(
            "skill_scout_query/v1 with intended workflow, triggers, domains/tools, and search keywords",
            "local_skill_candidate_inventory/v1 separating installed, bundled, marketplace, and repo-local matches when observed",
            "awesome_hermes_agent_coverage/v1 mapping upstream ecosystem entries to OMH covered, partial, or missing_candidate coverage statuses, matched OMH surfaces, rule_set_version, and matched_rule_id",
            "skill_adoption_decision_matrix/v1 ranking use existing, fork or extend, and create fresh options with trust gaps",
        ),
        final_checklist=(
            "Intent, keywords, source scope, and stop condition are explicit.",
            "Local and external search evidence is separated from planned search.",
            "No install, copy, write, credential, or trust claim is made without observed review or implementation.",
        ),
        recovery_notes=(
            "If the request is about setup or installed skill repair, route to doctor.",
            "If the request is a portfolio health dashboard, route to skill-health.",
            "If the request is an approved skill mutation or creation task, route to skill or implementation after the scout decision.",
        ),
    ),
    _feature_surface_skill(
        "skill-health",
        "Skill Health workflow: prepare a metadata-only OMH skill portfolio dashboard with stale surfaces, observed failure signals, pending amendments, and top actions.",
        (
            "skill-health",
            "skill health",
            "skill portfolio health",
            "skill dashboard",
            "skill health dashboard",
            "skill failure pattern dashboard",
            "skill failure patterns",
            "pending skill amendments",
            "skill amendments",
            "스킬 헬스",
            "스킬 상태",
            "스킬 대시보드",
            "스킬 실패 패턴",
            "스킬 개선 후보",
            "스킬 보류 수정",
        ),
        "Use when operators need portfolio-level skill health without treating it as install repair, live execution success, or automatic skill mutation.",
        category="operations",
        phase="skill-health",
        next_action="prepare_skill_health",
        boundary="A skill health dashboard is not install/setup health, live skill execution success, automatic skill mutation, model training, verification, review, CI, or proof that future routing is fixed.",
        good_prompt="skill-health show the OMH skill portfolio dashboard with stale surfaces, failure patterns, pending amendments, and top improvement actions.",
        bad_prompt="skill-health claim every skill is working and patch the failures automatically without observed signals or review.",
        expected_outputs=(
            "skill_portfolio_health_dashboard/v1",
            "skill_failure_pattern_clusters/v1 when observed",
            "pending_skill_amendment_review/v1",
            "skill_health_action_plan/v1",
        ),
        artifact_expectations=(
            "skill_portfolio_health_dashboard/v1 with catalog, generated, reference, harness, and capability-surface status",
            "skill_failure_pattern_clusters/v1 only from supplied traces, tests, reviews, missed routes, or wrapper observations",
            "skill_health_action_plan/v1 with top actions, owner lane, verification path, and non-mutation boundary",
        ),
        final_checklist=(
            "Dashboard scope, source surfaces, stale/duplicate criteria, and stop condition are explicit.",
            "Install/setup health is routed to doctor; catalog operations are routed to skill; failure retrospectives are routed to workflow-learning.",
            "No skill, prompt, doc, memory, or model behavior is claimed changed until a reviewed implementation records evidence.",
        ),
        recovery_notes=(
            "If the request is about OMH setup, install, stale package paths, or command availability, route to doctor.",
            "If the request is a missed-route or self-improvement trace, route to workflow-learning before adding health actions.",
        ),
    ),
    _feature_surface_skill(
        "workflow-learning",
        "Hermes workflow learning workflow: classify and review self-improvement store routes as an auxiliary review lane before durable writes, then record workflow attempts as metadata-only traces, evals, review queues, patch proposals, regression cases, audits, indexes, and exports.",
        (
            "workflow-learning",
            "workflow learning",
            "route-signal",
            "self-improvement store routing",
            "store route review",
            "memory skill wiki routing",
            "learning trace",
            "learning audit",
            "self improvement store routing",
            "store routing",
            "where should this learning go",
            "audit learning",
            "learning review",
            "review queue",
            "review-route",
            "store-routes",
            "learning readiness",
            "learning export",
            "export bundle",
            "learning index",
            "index rebuild",
            "execution trace",
            "skill improvement",
            "improvement candidate",
            "regression corpus",
            "GEPA",
            "VPRM",
            "process supervision",
            "why did this route",
            "missed route",
            "missed workflow",
            "did not use OMH",
            "OMH was not used",
            "learn from this run",
            "이번 실행 학습",
            "스킬 개선",
            "회귀 케이스",
            "실행 기록",
            "학습 기록",
            "학습 점검",
            "학습 준비 상태",
            "학습 내보내기",
            "OMH 안 썼어",
            "워크플로 누락",
            "라우팅 누락",
        ),
        "Use after a Hermes/OMH workflow attempt should become inspectable, evaluable, routed to memory/skill/wiki/failure-retrospective/automation review, persisted as a metadata-only store-route decision, queued for review, audited, replayable as a regression, converted to a patch handoff, exported, repaired after index drift, or captured as a missed-route signal without raw prompts. Store-route records are an auxiliary review lane surfaced by `learning review` and `learning store-routes`; they are not canonical learning index/export records until a reviewed destination produces its own artifact.",
        category="optimization",
        phase="workflow-learning",
        next_action="record_workflow_learning_trace",
        boundary="A workflow learning trace, self-improvement store route, patch proposal, or export is process evidence for review. It is not automatic model training, memory mutation, skill mutation, wiki write, automation creation, execution, verification, CI, or merge evidence.",
        good_prompt="workflow-learning route this self-improvement note before deciding whether it is memory, skill, wiki, failure-retrospective, or automation material.",
        bad_prompt="workflow-learning silently patch the skill and claim future behavior is fixed.",
    ),
)
